import type { LandingContent } from "@/types/content";
import { withBasePath } from "@/lib/paths";

export const landingContent: LandingContent = {
  hero: {
    title: "Алексей Иванов и Джем-Бэнд",
    lead: "Ведущий и живая кавер-группа для корпоративов и мероприятий в Татарстане.",
    bullets: ["Альметьевск", "Татарстан", "Живая программа"],
    primaryCtaLabel: "Обсудить мероприятие",
    secondaryCtaLabel: "Проверить дату",
    mediaId: "jam-band-hero-fon",
  },
  positioning: [
    "Алексей работает как ведущий мероприятий и как музыкант, поэтому программа может быть собрана вокруг живого контакта с залом и музыкальной части.",
    "Ключевая возможность продукта — заказать ведущего вместе с кавер-группой Джем-Бэнд как единую программу для новогоднего корпоратива.",
  ],
  host: {
    title: "Ведущий Алексей Иванов",
    description: [
      "Алексей ведет мероприятия на русском языке, играет на гитаре и поет. Юмор и импровизация помогают держать живой контакт с гостями.",
      "Визуальный прототип оставляет место для подтвержденных фото, видео и отзывов без вымышленных фактов о клиентах или наградах.",
    ],
    facts: ["Ведущий мероприятий", "Гитарист и вокалист", "Юмор и импровизация с гостями", "Работа в Альметьевске и близлежащих городах"],
    mediaId: "alexey-portrait-guitar",
  },
  band: {
    title: "Кавер-группа Джем-Бэнд",
    description: [
      "Джем-Бэнд — кавер-группа из четырех человек. Группа может усилить программу живым выступлением и закрыть музыкальную часть мероприятия.",
      "Алексей взаимодействует с музыкантами по ходу программы, поэтому группа может быть частью ведения, а не только отдельным концертным блоком.",
    ],
    membersCount: 4,
    repertoireLanguages: ["русский", "татарский", "английский"],
    mediaId: "jam-band-live-section",
  },
  experience: [
    "мероприятия различного масштаба",
    "опыт работы на событиях до 200 человек",
    "есть профессиональные фотографии ведущего",
    "есть видео ведущего с мероприятий",
    "есть видео группы со свадьбы",
    "есть видео акустического выступления группы на городском мероприятии",
  ],
  repertoire: {
    hostingLanguages: ["русский"],
    musicLanguages: ["русский", "татарский", "английский"],
    note: "Татарский репертуар нужно раскрыть подробнее после получения подтвержденного списка песен.",
  },
  servicePackages: [
    {
      id: "host",
      title: "Алексей Иванов",
      shortDescription: "Базовый формат для корпоратива с ведущим и техническим сопровождением.",
      features: ["ведущий", "звукооператор", "звуковая аппаратура"],
      price: 60000,
      pricePrefix: "от",
      priceSuffix: "₽",
      showPrice: false,
      priceFallbackText: "Стоимость рассчитывается индивидуально",
      featured: false,
      ctaLabel: "Узнать стоимость",
    },
    {
      id: "host-band",
      title: "Алексей Иванов + Джем-Бэнд",
      shortDescription: "Расширенная программа с ведущим, звуком и живым выступлением кавер-группы.",
      features: ["ведущий", "звукооператор", "звуковая аппаратура", "кавер-группа Джем-Бэнд"],
      price: 95000,
      pricePrefix: "от",
      priceSuffix: "₽",
      showPrice: false,
      priceFallbackText: "Стоимость рассчитывается индивидуально",
      featured: true,
      ctaLabel: "Обсудить программу",
    },
  ],
  media: [
    {
      id: "jam-band-hero-fon",
      type: "image",
      src: withBasePath("/images/band/hero-fon.png"),
      poster: null,
      alt: "Джем-Бэнд на сцене с ведущим, вокалисткой и барабанщиком",
      title: "Джем-Бэнд на сцене",
      description: "Сценический кадр группы для главного первого экрана.",
      category: "band",
      featured: true,
      sortOrder: 1,
      placeholder: false,
    },
    {
      id: "alexey-hero-stage-wide",
      type: "image",
      src: withBasePath("/images/host/alexey-hero-stage-wide.jpg"),
      poster: null,
      alt: "Алексей Иванов с гитарой и микрофоном на сцене",
      title: "Алексей Иванов на сцене",
      description: "Широкий сценический кадр для главного первого экрана.",
      category: "host",
      featured: true,
      sortOrder: 3,
      placeholder: false,
    },
    {
      id: "alexey-stage-guitar",
      type: "image",
      src: withBasePath("/images/host/alexey-stage-guitar.jpg"),
      poster: null,
      alt: "Алексей Иванов с гитарой и микрофоном на сцене",
      title: "Алексей Иванов на сцене",
      description: "Сценический кадр для первого экрана: ведущий, вокал и гитара в одном образе.",
      category: "host",
      featured: true,
      sortOrder: 5,
      placeholder: false,
    },
    {
      id: "alexey-portrait-guitar",
      type: "image",
      src: withBasePath("/images/host/alexey-portrait-guitar.jpg"),
      poster: null,
      alt: "Портрет Алексея Иванова с гитарой",
      title: "Портрет Алексея",
      description: "Портретный кадр для блока о ведущем.",
      category: "host",
      featured: true,
      sortOrder: 12,
      placeholder: false,
    },
    {
      id: "jam-band-live-wide",
      type: "image",
      src: withBasePath("/images/band/jam-band-live-wide.jpg"),
      poster: null,
      alt: "Джем-Бэнд выступает на мероприятии",
      title: "Джем-Бэнд live",
      description: "Живой кадр выступления кавер-группы на мероприятии.",
      category: "band",
      featured: true,
      sortOrder: 15,
      placeholder: false,
    },
    {
      id: "jam-band-live-section",
      type: "image",
      src: withBasePath("/images/band/jam-band-live-section.jpg"),
      poster: null,
      alt: "Джем-Бэнд во время живого выступления на мероприятии",
      title: "Джем-Бэнд live",
      description: "Кадр для основной секции кавер-группы.",
      category: "band",
      featured: true,
      sortOrder: 16,
      placeholder: false,
    },
    {
      id: "jam-band-vocal-live",
      type: "image",
      src: withBasePath("/images/band/jam-band-vocal-live.jpg"),
      poster: null,
      alt: "Вокалистка Джем-Бэнд во время живого выступления",
      title: "Вокал и гости",
      description: "Фото с живого выступления группы в банкетной атмосфере.",
      category: "event",
      featured: false,
      sortOrder: 18,
      placeholder: false,
    },
    {
      id: "band-acoustic-city",
      type: "image",
      src: withBasePath("/images/band/jam-band-acoustic-city.jpg"),
      poster: null,
      alt: "Акустическое выступление группы на открытой площадке",
      title: "Акустическое выступление",
      description: "Фото из текущих материалов проекта. Для финального hero желательно добавить отдельный кадр с корпоративной атмосферой.",
      category: "acoustic",
      featured: true,
      sortOrder: 10,
      placeholder: false,
    },
    {
      id: "host-acoustic",
      type: "image",
      src: withBasePath("/images/host/alexey-acoustic-performance.jpg"),
      poster: null,
      alt: "Алексей Иванов с гитарой у микрофона",
      title: "Ведущий и музыка",
      description: "Фото из текущих материалов проекта для секции ведущего и музыканта.",
      category: "host",
      featured: true,
      sortOrder: 20,
      placeholder: false,
    },
    {
      id: "alexey-stage-mic",
      type: "image",
      src: withBasePath("/images/host/alexey-stage-mic.jpg"),
      poster: null,
      alt: "Алексей Иванов у микрофона с гитарой на сцене",
      title: "Ведущий у микрофона",
      description: "Сценический кадр Алексея для дополнительной фотогалереи.",
      category: "host",
      featured: false,
      sortOrder: 22,
      placeholder: false,
    },
    {
      id: "alexey-motion-white",
      type: "image",
      src: withBasePath("/images/host/alexey-live-hosting.jpg"),
      poster: null,
      alt: "Алексей Иванов ведет мероприятие с микрофоном",
      title: "Живое ведение",
      description: "Кадр с ведущим в живом формате на площадке.",
      category: "host",
      featured: false,
      sortOrder: 24,
      placeholder: false,
    },
    {
      id: "jam-band-banquet-live",
      type: "image",
      src: withBasePath("/images/band/jam-band-banquet-live.jpg"),
      poster: null,
      alt: "Джем-Бэнд выступает перед гостями на мероприятии",
      title: "Музыка в зале",
      description: "Кадр с выступления группы и живой реакцией зала.",
      category: "corporate",
      featured: false,
      sortOrder: 26,
      placeholder: false,
    },
    {
      id: "jam-band-acoustic-stage",
      type: "image",
      src: withBasePath("/images/band/jam-band-acoustic-stage.jpg"),
      poster: null,
      alt: "Акустическое выступление с вокалом и гитарой на сцене",
      title: "Акустический формат",
      description: "Кадр акустического выступления для показа более спокойного музыкального формата.",
      category: "acoustic",
      featured: false,
      sortOrder: 28,
      placeholder: false,
    },
    {
      id: "showreel-todo",
      type: "video",
      src: null,
      poster: withBasePath("/images/band/jam-band-vocal-live.jpg"),
      alt: "SHOWREEL TODO: место для будущего видеоролика",
      title: "SHOWREEL — TODO",
      description: "Крупный слот под будущий showreel. Сейчас файл отсутствует и видео не загружается.",
      category: "showreel",
      featured: true,
      sortOrder: 30,
      placeholder: true,
    },
  ],
  reviews: [],
  faq: [
    {
      id: "cities",
      question: "В каких городах можно провести мероприятие?",
      answer: "Основной город — Альметьевск. Также возможны Бугульма, Нижнекамск, Набережные Челны и близлежащие города по договоренности.",
    },
    {
      id: "languages",
      question: "На каких языках проходит программа?",
      answer: "Ведение проходит на русском языке. Песни и музыкальный репертуар могут быть на русском, татарском и английском.",
    },
  ],
  availableDates: [
    {
      date: "12 декабря",
      status: "available",
      note: "Демонстрационное значение, требуется подтверждение владельцем",
      placeholder: true,
    },
    {
      date: "19 декабря",
      status: "booked",
      note: "Демонстрационное значение, требуется подтверждение владельцем",
      placeholder: true,
    },
    {
      date: "20 декабря",
      status: "booked",
      note: "Демонстрационное значение, требуется подтверждение владельцем",
      placeholder: true,
    },
    {
      date: "26 декабря",
      status: "limited",
      note: "Демонстрационное значение, требуется подтверждение владельцем",
      placeholder: true,
    },
  ],
};
